[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Optional: redirect SPA routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
