[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Single Page App routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Never cache our live price function
[[headers]]
  for = "/.netlify/functions/get-prices"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"
    Vary = "Origin"
