[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[scheduled.functions]]
  name = "bot-scheduler"
  cron = "* * * * *"
